export const jobs = [
  {
    id: 1,
    slug: "electrical-sales-engineer",
    title: "Electrical Sales Engineer",
    company: "Electrical Devices Mfg. Company",
    client: "Electrical Devices Mfg. Company @ Pashan–Sus Road (Pune)",
    location: "Pashan–Sus Road, Pune",
    jobType: "Full Time",
    vacancies: 4,
    gender: "Male",
    education: "Diploma / BE – Electrical / Electronics",
    experience: "Fresher to 5 Years",
    salary: "₹20,000 – ₹40,000 PM",
    benefits: [
      "Incentives",
      "Travelling Allowances",
    ],
    workingHours: "10:00 AM – 6:00 PM",
    weeklyOff: "Sunday",
    joining: "Immediate / 15 Days",
    vehicleRequired: "Motorcycle (Mandatory)",
    description: [
      "Working as Electrical Sales Engineer in electrical components.",
      "50% office-based work and 50% field job with clients.",
      "Candidate must be based in Pune.",
      "Must have own motorcycle for client visits.",
    ],
  },

  {
    id: 2,
    slug: "frontend-developer",
    title: "Frontend Developer",
    company: "Job Leads Pvt. Ltd.",
    client: "Job Leads Pvt. Ltd.",
    location: "Bangalore / Remote",
    jobType: "Full Time",
    vacancies: 2,
    gender: "Any",
    education: "BE / BTech / MCA",
    experience: "2–4 Years",
    salary: "₹8 – ₹12 LPA",
    benefits: ["WFH", "Health Insurance"],
    workingHours: "10:00 AM – 7:00 PM",
    weeklyOff: "Saturday & Sunday",
    joining: "30 Days",
    vehicleRequired: "Not Required",
    description: [
      "Develop UI using React & Next.js",
      "Collaborate with backend and design teams",
      "Optimize applications for performance",
    ],
  },
];